server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/storage
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:29092

minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket: reports

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
