spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://orders-db:5432/appdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: kafka:9092
    consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    consumer:
      properties:
        spring.json.trusted.packages: com.asyncshopping.*

  task:
    scheduling:
      pool:
        size: 5


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
    com.asyncshopping.orderservice: DEBUG