server:
  port: 8082

spring:
  codec:
    max-in-memory-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5434/analysis
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: localhost:29092

storage:
  url: http://localhost:8081

quickchart:
  base-url: https://quickchart.io/wordcloud

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
