server:
  port: 8082

spring:
  application:
    name: file-analysis-service
  datasource:
    url: jdbc:postgresql://file-analysis-db:5432/file_analysis_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

word-cloud:
  api:
    url: https://quickchart.io/wordcloud
    timeout: 5000

file-storage:
  service:
    url: http://file-storage-service:8081